name: "Build and Deploy"
on:
  push:
    branches:
      - main
    paths-ignore:
      - .gitignore
      - README.md
      - LICENSE

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # checkout the repo code
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout deploy branch
        uses: actions/checkout@v2
        with:
          ref: deploy
      - name: Copy _site contents to deploy branch
        run: cp -R _site/* .
      - name: Commit changes
        run: |
          git config --global user.name 'Spencer'
          git config --global user.email 'smaroukis@gmail.com'
          git commit -a -m "Deploy site"
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
